--
-- CONTENT FOR DATABASE
--

INSERT INTO brands(name, created_at, updated_at)
VALUES ('Samsung', now(), now()),
       ('Huawei', now(), now()),
       ('Xiaomi', now(), now()),
       ('Lenovo', now(), now()),
       ('Nokia', now(), now()),
       ('Sony', now(), now()),
       ('Apple', now(), now());


INSERT INTO smartphones(name, price, brand_id, description, ram, operating_system, os_version, display_size,
                        resolution, height, width, thickness, color, created_at, updated_at)
VALUES ('Samsung Galaxy A52 6GB/128GB', 189.99, 1,
        'Elegantný smartfón s veľkým displejom, ktorý chráni oči a zobrazuje všetko plynulo a čitateľne, nech už sú okolité podmienky akékoľvek. Štyri objektívy fotoaparátu vytvoria ultraširokouhlé snímky, stabilný a jasný obraz, rozostrené pozadie aj makro fotografie. Stabilné sú aj videá a selfie portréty vo vysokom rozlíšení. Telefón je vodoodolný, takže si s ním môžete ísť pokojne zaplávať. Veľkokapacitná batéria vydrží celý víkend a rýchlonabíjanie sa postará o dodanie energie bez zbytočného zdržiavania. K lepšiemu zážitku z hrania hier prispeje Game Booster a dva špičkové reproduktory. Vďaka Samsung Knox a snímaču odtlačkov prstov je Galaxy A52 zabezpečený na jednotku.',
        6144, 'Android', 11, 6.5, '2400 x 1080', 159.9, 75.1, 8.4, 'Žltá', now(), now()),
       ('Xiaomi Redmi Note 10 Pro 6GB/128GB', 299.00, 3,
        'Špičkovo vybavený fotoaparát zaujme každého, kto si rád uchováva spomienky vo forme snímok a videí. S ohromnou ponukou funkcií a režimov vás práca fotografa bude baviť omnoho viac. Vytvorte neobyčajné snímky, na ktorých budete hneď niekoľkokrát, alebo nakombinujte obrazy z prednej a zadnej kamery do jedného. Vďaka dlhej výdrži batérie môžete vyraziť na výlet aj bez nabíjačky a s výkonným procesorom vás nebude pri práci nič zdržiavať. Trojrozmerný zvuk znamená viac zábavy pri pozeraní filmov aj hraní hier. To všetko v inteligentnom telefóne s nadčasovým dizajnom.',
        6144, 'Android', 11, 6.67, '2400 x 1080', 164, 76.5, 8.1, 'Čierna', now(), now()),
       ('Apple iPhone 12 128GB', 818.90, 7,
        'Dvanásta generácia obľúbeného smartfónu vás svojou výbavou určite nesklame. Výkonný procesor zvládne aj náročné operácie v priebehu okamihu a navyše je energeticky nenáročný. Prakticky bezrámčekový displej hrá všetkými farbami a jednotlivé pixely majú samostatné podsvietenie, takže si všetok obsah vychutnáte v ešte lepšom podaní. Zariadenie podporuje mobilné siete 5G, vďaka čomu môžete sťahovať, telefonovať aj sledovať online prenosy v skvelej kvalite. Dvojitý fotoaparát disponuje množstvom funkcií a efektov, s ktorými každú snímku aj video dotiahnete k dokonalosti. A navyše je iPhone 12 odolný proti prachu, vode aj nárazu.',
        4096, 'iOS', 14, 6.1, '2532 x 1170', 146.7, 71.5, 7.4, 'Čierna', now(), now()),
       ('Apple iPhone 11 64GB', 638.00, 7,
        'Hlavným lákadlom, na ktorý sa spoločnosť Apple najviac zamerala, je dlho očakávaná fotosústava so širokouhlým a ultraširokouhlým záberom, ktorá vám dovolí zachytiť scénu v celej svojej kráse a navyše poskytne až dvojnásobný optický zoom. Okrem toho ponúkne úchvatný nočný režim, s ktorým môžete fotiť aj v hlbokej tme. Pozadu nezostalo ani video s rozlíšením 4K pri 60 snímkach za sekundu či spomalený režim s až 240 snímkami vo Full HD. Toto všetko bez zaváhania spracuje nový procesor A13 Bionic s ultrarýchlou grafickou jednotkou, ktorá si poradí s akokoľvek náročnou hrou či aplikáciou. Telo sa chváli najodolnejším sklom na trhu a obsahuje batériu, ktorá vydrží až 17 hodín prehrávať video a rýchlo sa nabije.',
        4096, 'iOS', 13, 6.1, '1792 x 828', 150.9, 75.7, 8.3, 'Ružová', now(), now()),
        ('Samsung Galaxy S20 6GB/128GB Dual SIM', 468.00, 1,
        'Inteligentnému telefónu od spoločnosti Samsung nič nechýba. Trojitý fotoaparát ponúka množstvo rôznych funkcií a režimov, vďaka ktorým budú vaše snímky kvalitnejšie ako kedykoľvek predtým. Predný objektív s vysokým rozlíšením sa postará o ostré a realistické selfie fotky. Výkonný procesor, 6 GB pamäť RAM a podpora LTE a Wi-Fi 6 zaistia bezchybný a plynulý chod telefónu a veľké vnútorné úložisko s podporou pamäťovej karty pojme viac aplikácií, hier, filmov a pesničiek, ako budete potrebovať. Galaxy S20 FE je navyše vodoodolný, kompatibilný s ďalšími zariadeniami a vyrába sa v niekoľkých farebných prevedeniach, takže si vyberie aj ten najnáročnejší používateľ.',
        6144, 'Android', 10, 6.5, '2400 x 1080', 159.8, 74.5, 8.4, 'Ružová', now(), now()),
        ('Samsung Galaxy S21 5G 8GB/128GB', 705.90, 1,
        'Vodoodolný telefón od Samsungu je prepracovaný zo všetkých strán. Má veľký displej s plynulým obrazom a ochranou pre oči a navyše je obrazovka chránená odolným sklom Corning Gorilla. Nakrúca 8K stabilné a superplynulé videá, z ktorých potom vytvorí aj fotografie. Dokáže fotiť aj v tme tak, aby boli výsledné snímky perfektne viditeľné. Batéria sa nabije v priebehu chvíľky a o energiu sa dokáže podeliť aj s inými zariadeniami. Okrem toho je smartfón zabezpečený ochranou Knox, vie pracovať s 5G a pripojí sa k televízoru aj počítaču.',
        8192, 'Android', 11, 6.2, '2400 x 1080', 151.7, 71.2, 7.9, 'Zelená', now(), now()),
        ('Samsung Galaxy A12 4GB/64GB', 178.90, 1,
        'Inteligentný mobilný telefón Samsung Galaxy A12 v sebe kombinuje nadupané vybavenie s elegantným moderným dizajnom. Poteší vás osemjadrovým procesorom, štvornásobným fotoaparátom so 48 Mpix i veľkokapacitnou batériou. Všetok obsah si pozriete na špičkovom Infinity-V displeji so 6,5-palcovou uhlopriečkou a HD+ rozlíšením. Smartfón je vybavený Androidom s množstvom inteligentných funkcií a viacvrstvovým zabezpečením. Dizajn telefónu vám padne do oka vďaka krásnym farbám i nadčasovému spracovaniu.',
        4096, 'Android', 10, 6.5, '1600 x 720', 164.0, 75.8, 8.9, 'Čierna', now(), now()),
        ('Xiaomi Redmi 9A 2GB/32GB', 109.99, 3,
        'Jednoduchý dizajn so zadnou stranou, ktorá odolá odtlačkom prstov, sa nestratí na večierku ani na pracovnom stretnutí. Takmer bezrámčekový displej s kvapkovitým výrezom vyžaruje menej modrého svetla, a preto vás ani pri dlhodobej práci na telefóne nebudú bolieť oči. Veľkokapacitná batéria vám umožní používať smartfón počas celého dňa bez nutnosti nabitia a vďaka dlhšej životnosti si jej kvality môžete užívať ešte dlhšie, ako by ste čakali. S výkonným procesorom, zamykaním obrazovky pomocou tváre a fotoaparátom s umelou inteligenciou bude používanie telefónu ešte zábavnejšie a bezpečnejšie.',
        2048, 'Android', 10, 6.53, '1600 x 720', 164.9, 77.07, 9, 'Čierna', now(), now()),
        ('Xiaomi Redmi Note 9 Pro 6GB/128GB', 239.00, 3,
        'Štyri rôzne objektívy fotoaparátu zvečnia akýkoľvek moment ako živý a so selfie kamerou sa vám podarí zachytiť svoje portréty aj v slow-motion verzii. Natáčanie videí bude ešte jednoduchšie vďaka množstvu rôznych filtrov, režimov a módov, s ktorými jednoducho vytvoríte vlogy aj krátke filmy. V telefóne je pripravená aj aplikácia na skenovanie a úpravu dokumentov, ktorú využijete pri práci. Dlhá výdrž batérie spolu s výkonným procesorom zvládnu aj tie najnáročnejšie požiadavky a poradia si s akýmkoľvek programom alebo hrou. Všetko budete mať zabezpečené odtlačkom prsta.',
        6144, 'Android', 10, 6.67, '2340 x 1080', 165.75, 76.68, 8.8, 'Sivá', now(), now()),
        ('Huawei P30 Lite 4GB/128GB Dual SIM', 209.90, 2,
        'Prepracovaný telefón s veľkým displejom a elegantným designom, vďaka ktorému sa i kvôli veľkým rozmerom obrazovky ľahko ovláda jednou rukou. Naviac je rýchly a má veľký výkon, ktorý vám bude stačiť i pri náročnom hraní hier, takže sa nemusíte obávať nepríjemného sekania a pomalého načítania. Veľká užívateľská pamäť, rýchle nabíjanie a perfektné spracovanie grafiky vám prácu s telefónom ešte viac spríjemnia. Okrem toho na vás čaká fotoaparát, ktorý sa postará o snímky kvalitou porovnateľné s hociktorými profesionálnymi príjstrojmi. A, samozrejme, plno ďalších vylepšení, ktoré vám uľahčia prácu.',
        4096, 'Android', 9, 6.15, '2312 x 1080', 152.9, 72.7, 7.4, 'Sivá', now(), now()),
        ('Huawei P Smart 2021 Dual SIM', 199.99, 2,
        'Inteligentný telefón od Huawei vás naláka už svojim kvalitným spracovaním a modernými farbami. Elegantný vzhľad podtrhne veľký displej s vysokým rozlíšením alebo čítačka odtlačkov prstov, ktorú nájdete na bočnej strane prístroja. Nechýba ani veľká používateľská pamäť a úsporná batéria s rýchlym nabíjaním. Štvornásobný fotoaparát je pripravený na všetko, s čím by ste sa mohli stretnúť. Disponuje ultraširokouhlým objektívom, makro objektívom, hĺbkovým objektívom a hlavnou kamerou s vysokým rozlíšením.',
        4096, 'Android', 10, 6.67, '1400 x 1080', 165.65, 76.88, 9.26, 'Zelená', now(), now()),
        ('Huawei P40 Lite 6GB/128GB Dual SIM', 219.99, 2,
        'Chytrý telefón Huawei P40 Lite poteší každého milovníka mobilných technológií. V jeho vybavení objavíte pokročilý štvornásobný fotoaparát, nadupaný výkon i inteligentné prostredie. Urobíte s ním parádne snímky vo dne aj v noci a tešiť sa môžete aj na plynulý chod a dostatočnú pamäť. Vydarený dizajn svojím decentným spracovaním doplní akýkoľvek štýl. Vďaka vysokokapacitnej batérii vám telefón vydrží v prevádzke aj po dlhý deň a pomocou technológie rýchleho nabíjania mu dodáte stratenú energiu prekvapivo rýchlo.',
        6144, 'Android', 10, 6.4, '2310 x 1080', 159.2, 76.3, 8.7, 'Žltá', now(), now()),
        ('Lenovo K10 Note 6/128', 199.00, 4,
        'Mobilný telefón Lenovo K10 Note vás zaujme elegantným telom bez rámikov, ktorému dominuje veľký displej cez celú prednú plochu. Srdcom telefónu je výkonný 8-jadrový procesor so 6 GB pamäťou RAM na rýchlu odozvu systému Android 9 a všetkých aplikácií a hier. Na ukladanie dát je k dispozícii veľká vnútorná pamäť s kapacitou 128 GB s možnosťou jej rozšírenia pomocou pamäťovej karty do veľkosti až 256 GB. Na zabezpečenie telefónu sa na zadnej strane nachádza čítačka odtlačkov prstov.',
        6144, 'Android', 9, 6.3, '2340 x 1080', 156.6, 74.3, 7.9, 'Biela', now(), now()),
        ('Nokia G10', 129.90, 5,
        'Nokia G10 disponuje rafinovaným škandinávskym dizajnom inšpirovaným severskými farbami a zaujme všetkých, ktorí ocenia praktickú eleganciu v kombinácii s najmodernejšou technológiou. Telefón ponúka kvalitný zadný fotoaparát s rozlíšením 13 + 2 + 2 Mpx, fotovýbavy okrem hlavného objektívu ponúkne makro aj hĺbkový objektív. Nechýba kvalitný portrétny a nočný režim, ktoré zaistia farebné a ostré fotografie aj za horších svetelných podmienok. Kvalitné selfie zaistí 8 Mpx predná kamera. Fotografie si v plnej farebnosti vychutnáte na dotykovom IPS LCD displeji s HD+ rozlíšením 1600×720 px a veľkosťou 6,52 palcov, ktorá poskytne dokonalý zážitok pri sledovaní videí, hraní hier alebo surfovaní na internete!',
        3072, 'Android', 11, 6.5, '1600 x 720', 164.9, 76.0, 9.2, 'Biela', now(), now()),
        ('Nokia 8000 Dual Sim', 75.90, 5,
        'Držte krok s modernými technológiami. Nokia 8000 4G podporuje rýchle mobilné siete LTE, zostanete tak vždy v spojení s okolitým svetom! Vďaka sociálnym a komunikačným platformám Whatsapp a Facebook sa ľahko spojíte s vašimi priateľmi, môžete tiež streemovať videá na YouTube alebo pomocou Google Map plánovať cestovateľské dobrodružstvo. Funkcia Asistenta Google zabezpečí potrebné informácie stlačením jedného tlačidla, poteší aj WiFi, Bluetooth a polohový senzor A-GPS! Pre počúvanie hudby je telefón vybavený 3,5 mm slúchadlovým konektorom, nechýba ani microUSB port. Interné úložisko možno navyše rozšíriť až o 32GB vďaka integrovanému slotu na pamäťovú kartu a telefón sa pýši aj Dual SIM!',
        512, 'Android', 9, 2.8, '320 x 240', 132.2, 56.5, 12.3, 'Červená', now(), now()),
        ('Sony Xperia 10 6GB/128GB Dual SIM', 403.09, 6,
        'Moderný design, vysoký výkon, rýchlosť 5G, spoľahlivá batéria, rýchle nabíjanie, vodoodolné telo. To je iba niekoľko výhod modelu Sony Xperia 10 III. Ponúka tiež tri objektívy - širokouhlý, všestranný a teleobjektív, takže sa stanete autorom dych vyrážajúcich expresívnych portrétov, momentiek či záberov rôznorodej krajiny plných detailov. Automatický režim navyše ponúka funkciu rozoznávania zvierat, upraví expozíciu a dohliadne na to, aby bola fotografia maximálne ostrá. Podarí sa vám zachytiť menu v reštaurácii, podvečernú kompozíciu pri minimálnom osvetlení, detail tváre v protisvetle či pohyb. Telefón vyhotoví aj kvalitné videozáznamy v 4K rozlíšení (štvornásobok Full HD).',
        6000, 'Android', 11, 6.0, '2520 x 1080', 154.0, 68.0, 8.3, 'Červená', now(), now()),
        ('Sony Xperia 1 12GB/256GB', 1299.00, 6,
        'Tento smartphone si vás získa unikátnym designom odolným voči vode i prachu a prekvapujúcou výdržou batérie. Jeho najdôležitejšou prednosťou je však fotoaparát so štyrmi objektívmi, ktorý automaticky zaostrí aj na pohybujúce sa objekty. Disponuje tiež sofistikovaným snímačom 3D iToF a množstvom režimov. Technológia CineAlta umožní nakrúcanie filmov s nastavením farieb a parametrov podobným tým, aké používajú profesionálni filmoví tvorcovia. Svoje výtvory si následne prezriete na inovovanom 4K HDR OLED displeji.',
        12288, 'Android', 11, 6.5, '1644 x 3840', 165.0, 71.0, 8.2, 'Modrá', now(), now()),
        ('Sony Xperia 5', 999.00, 6,
        'Smartfón Xperia 5 III je kompaktný, výkonný a kombinuje rýchle AF jeho predchodcu s novou optikou s ohniskovou vzdialenosťou až 105 mm. Či už fotíte alebo hráte hry, padne vám do ruky a prekoná vaše očakávania.',
        8192, 'Android', 10, 6.1, '2520 x 1080', 157.0, 68.0, 8.2, 'Modrá', now(), now());


INSERT INTO images(name, source, smartphone_id, created_at, updated_at)
VALUES ('Xiaomi smartphone', '/images/smartphone-1.jpg', 2, now(), now()),
       ('Samsung smartphone', '/images/smartphone-2.jpg', 1, now(), now()),
       ('Apple smartphone', '/images/smartphone-3.jpg', 3, now(), now()),
       ('Xiaomi smartphone', '/images/smartphone-4.jpg', 8, now(), now()),
       ('Huawei smartphone', '/images/smartphone-5.jpg', 10, now(), now()),
       ('Samsung smartphone', '/images/smartphone-6.jpg', 2, now(), now()),
       ('Apple smartphone', '/images/smartphone-7.jpg', 3, now(), now()),
       ('Apple smartphone', '/images/smartphone-8.jpg', 4, now(), now()),
       ('Apple smartphone', '/images/smartphone-9.jpg', 4, now(), now()),
       ('Sony smartphone', '/images/smartphone-10.jpg', 17, now(), now()),
       ('Nokia smartphone', '/images/smartphone-11.jpg', 14, now(), now()),
       ('Lenovo smartphone', '/images/smartphone-12.jpg', 13, now(), now()),
       ('Samsung smartphone', '/images/smartphone-13.jpg', 7, now(), now()),
       ('Samsung smartphone', '/images/smartphone-14.jpg', 6, now(), now()),
       ('Samsung smartphone', '/images/smartphone-15.jpg', 5, now(), now()),
       ('Xiaomi smartphone', '/images/smartphone-16.jpg', 9, now(), now()),
       ('Sony smartphone', '/images/smartphone-17.jpg', 18, now(), now()),
       ('Sony smartphone', '/images/smartphone-18.jpg', 16, now(), now()),
       ('Nokia smartphone', '/images/smartphone-19.jpg', 15, now(), now()),
       ('Huawei smartphone', '/images/smartphone-20.jpg', 12, now(), now()),
       ('Huawei smartphone', '/images/smartphone-21.jpg', 11, now(), now()),
       ('Xiaomi smartphone', '/images/smartphone-22.jpg', 9, now(), now()),
       ('Xiaomi smartphone', '/images/smartphone-23.jpg', 9, now(), now());
